owner: casa-carreras
repo: status

# User agent personalizado para evitar bloqueos
user-agent: Mozilla/5.0 (compatible; Status/1.0)

sites:
  - name: "Shop"
    url: https://casa-carreras.es
    maxResponseTime: 30000

  - name: "Mail"
    url: mail.casa-carreras.es
    port: 25
    check: "tcp-ping"

  - name: "Webmail"
    url: https://webmail.casa-carreras.es
    maxResponseTime: 30000

  - name: "Backups"
    url: https://backup.casa-carreras.es
    maxResponseTime: 30000

scheduledMaintenances:
  - name: "Backup diario"
    description: "Los servicios pueden estar temporalmente no disponibles debido al backup automático."
    start: "03:00"
    end: "03:40"
    schedule: "0 3 * * *"  # Cambiar "cron" por "schedule"

status-website:
  cname: status.casa-carreras.es
  name: Pedraja Status
  logoUrl: https://casa-carreras.es/web/image/website/1/logo/Bellas%20Artes%20Casa%20Carreras?unique=cb91b6d 
  introTitle: "**Estado de los servicios de Casa Carreras**"
  introMessage: Monitoreo en tiempo real de nuestros servicios principales.
  theme: light
  
  navbar:
    - title: Status
      href: /
    - title: Sitio Web
      href: https://casa-carreras.es

# Notificaciones
assignees:
  - casacarreras

# Personalización
i18n:
  footer: "© 2025 Bellas Artes Casa Carreras"
  
commitMessages:
  commitAuthorName: "Casa Carreras Status Bot"
  commitAuthorEmail: "casa-carreras@casa-carreras.es"

skipDescriptionIssues: true
skipTopicsIssues: true

